name: 'Wayback Machine Query'
description: 'Query archive.org''s Wayback machine to get URLs of archived web pages'
author: 'David Gardiner'
branding:
  icon: archive
  color: blue
inputs:
  source-path:
    required: true
    description: 'Path to file to read JSON data from'
    default: './lychee/links.json'
  replacements-path:
    required: false
    description: '(Optional) Path to file to write replacement data to'
    default: './wayback/replacements.json'
  timestamp-regex:
    required: false
    description: (Optional) Regular expression to extract a timestamp from the input URL
outputs:
  replacements:
    description: JSON array of replacement data
  missing:
    description: JSON array of URLs that are missing
runs:
  using: 'node24'
  main: 'dist/index.js'

